apiVersion: v1
stringData:
  MYSQL_ROOT_PASSWORD: test
  MYSQL_DATABASE: test       
  MYSQL_USER: test           
  MYSQL_PASSWORD: test
  MYSQL_HOST: mariadb.app.svc.cluster.local  
kind: Secret
metadata:
  name: mariadb-secret
  namespace: app
  